# Generated by Django 2.2.10 on 2020-03-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client voornaam')),
                ('client_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Client achternaam')),
            ],
        ),
    ]
