# Generated by Django 2.2.10 on 2020-03-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200319_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='emailadres',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mailadres'),
        ),
        migrations.AddField(
            model_name='case',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geboortedatum'),
        ),
        migrations.AddField(
            model_name='case',
            name='geslacht',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Man'), (2, 'Vrouw'), (3, 'Overig')], null=True, verbose_name='Geslacht'),
        ),
    ]
