# Generated by Django 2.2.10 on 2020-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20200327_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='kinderen',
            field=models.TextField(blank=True, null=True, verbose_name='Kinderen'),
        ),
    ]
