# Generated by Django 2.2.10 on 2020-05-06 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200407_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titel van het document')),
                ('uploaded_file', models.FileField(upload_to='uploads', verbose_name='Selecteer een bestand')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Initieel opgeslagen datum/tijd')),
                ('saved', models.DateTimeField(auto_now=True, verbose_name='Opgeslagen datum/tijd')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='Cliënt')),
            ],
            options={
                'verbose_name': 'Bijlage',
                'verbose_name_plural': 'Bijlagen',
                'ordering': ('-uploaded',),
            },
        ),
    ]
