# Generated by Django 2.2.10 on 2020-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20200507_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='omklap_toelichting',
            field=models.TextField(blank=True, null=True, verbose_name='Toelichting (bv. doelen niet behaald maar geen risico voor zelfstandig wonen)'),
        ),
    ]
