# Generated by Django 2.2.10 on 2020-05-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_document_forms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'ingediend'), (2, 'afgekeurd'), (3, 'goedgekeurd'), (4, 'wachten op GGD')], default=1, verbose_name='Status')),
                ('status_comment', models.TextField(blank=True, null=True, verbose_name='Opmerking')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Initieel opgeslagen datum/tijd')),
                ('form', models.CharField(blank=True, max_length=100, null=True, verbose_name='Formulier')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case', verbose_name='Cliënt')),
                ('case_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.CaseVersion', verbose_name='Cliënt versie')),
            ],
            options={
                'verbose_name': 'Cliënt status',
                'verbose_name_plural': 'Cliënt statussen',
                'ordering': ('created', 'case', 'form'),
            },
        ),
    ]
