# Generated by Django 2.2.10 on 2020-05-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200325_1659'),
        ('cases', '0012_casestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestatus',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Profiel'),
        ),
    ]
