# Generated by Django 2.2.10 on 2020-06-10 09:04

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_casestatus_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestatus',
            options={'ordering': ('-created', 'case', 'form'), 'verbose_name': 'Cliënt status', 'verbose_name_plural': 'Cliënt statussen'},
        ),
        migrations.AddField(
            model_name='case',
            name='kinderen_check',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Nee'), (1, 'Ja')], null=True, verbose_name='Heeft de cliënt kinderen?'),
        ),
        migrations.AddField(
            model_name='case',
            name='partner_check',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Nee'), (1, 'Ja')], null=True, verbose_name='Heeft de cliënt een partner?'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='kinderen_check',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Nee'), (1, 'Ja')], null=True, verbose_name='Heeft de cliënt kinderen?'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='partner_check',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Nee'), (1, 'Ja')], null=True, verbose_name='Heeft de cliënt een partner?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='forms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['aanvraag-omslag-en-urgentie', 'Aanvraag Urgentie onder voorwaarden'], ['aanvraag-omklap', 'Aanvraag Voordracht omklap']], max_length=43, null=True, verbose_name='Formulieren'),
        ),
    ]
