# Generated by Django 2.2.10 on 2020-06-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200325_1659'),
        ('cases', '0015_auto_20200612_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Opgeslagen door'),
        ),
        migrations.AddField(
            model_name='case',
            name='saved_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formulier'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', verbose_name='Opgeslagen door'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='saved_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Formulier'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ingediend'), (2, 'afgekeurd'), (3, 'goedgekeurd'), (4, 'in behandeling')], default=1, verbose_name='Status'),
        ),
    ]
