# Generated by Django 2.2.10 on 2020-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_auto_20200615_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_derde',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Akkoord door onafhankelijke derde'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_derde_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum van akkoord'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_derde_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam / afdeling onafhankelijke derde'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_derde_toelichting',
            field=models.TextField(blank=True, null=True, verbose_name='Toelichting'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_derde',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Akkoord door onafhankelijke derde'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_derde_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum van akkoord'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_derde_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam / afdeling onafhankelijke derde'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_derde_toelichting',
            field=models.TextField(blank=True, null=True, verbose_name='Toelichting'),
        ),
    ]
