# Generated by Django 2.2.10 on 2020-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_auto_20200624_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='omklap_akkoord_derde',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Akkoord objectieve derde'),
        ),
        migrations.AlterField(
            model_name='case',
            name='omklap_akkoord_derde_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam / afdeling objectieve derde'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='omklap_akkoord_derde',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Akkoord objectieve derde'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='omklap_akkoord_derde_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam / afdeling objectieve derde'),
        ),
    ]
