# Generated by Django 2.2.10 on 2020-06-25 11:10

from django.db import migrations, models
import web.cases.models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_auto_20200625_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to=web.cases.models.get_upload_path, verbose_name='Selecteer een bestand'),
        ),
    ]
