# Generated by Django 2.2.10 on 2020-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20200625_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afgesloten datum'),
        ),
    ]
