# Generated by Django 2.2.10 on 2020-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_auto_20200625_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='delete_request_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verwijder verzoek datum'),
        ),
        migrations.AddField(
            model_name='case',
            name='delete_request_message',
            field=models.TextField(blank=True, null=True, verbose_name='Verwijder verzoek bericht'),
        ),
    ]
