# Generated by Django 2.2.10 on 2020-06-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200325_1659'),
        ('cases', '0020_auto_20200625_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='delete_request_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_list', to='profiles.Profile', verbose_name='Verwijder verzoek door'),
        ),
    ]
