# Generated by Django 2.2.10 on 2020-07-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_case_delete_request_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='wonen_dossier_nr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dossier nr.'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='wonen_dossier_nr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dossier nr.'),
        ),
    ]
