# Generated by Django 2.2.10 on 2020-07-06 09:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20200701_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='forms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['aanvraag-omslag-en-urgentie', 'Aanvraag Urgentie onder voorwaarden'], ['aanvraag-omklap', 'Aanvraag Voordracht omklap'], ['evaluatie-wonen', 'Evaluatie wonen']], max_length=59, null=True, verbose_name='Formulieren'),
        ),
    ]
