# Generated by Django 2.2.10 on 2020-07-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_auto_20200701_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='adres_huisnummer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Huisnummer'),
        ),
        migrations.AddField(
            model_name='case',
            name='adres_plaatsnaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plaatsnaam'),
        ),
        migrations.AddField(
            model_name='case',
            name='adres_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='case',
            name='adres_straatnaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straatnaam'),
        ),
        migrations.AddField(
            model_name='case',
            name='adres_toevoeging',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_huisnummer',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Huisnummer'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_plaatsnaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Plaatsnaam'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_straatnaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Straatnaam'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_toevoeging',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging'),
        ),
    ]
