# Generated by Django 2.2.10 on 2020-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_auto_20200702_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='adres_wijziging_reden',
            field=models.TextField(blank=True, null=True, verbose_name='Waarom wijzig je dit adres?'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='adres_wijziging_reden',
            field=models.TextField(blank=True, null=True, verbose_name='Waarom wijzig je dit adres?'),
        ),
    ]
