# Generated by Django 2.2.10 on 2020-07-08 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200325_1659'),
        ('cases', '0024_auto_20200706_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='woningcorporatie_medewerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_case_set', to='profiles.Profile', verbose_name='Woningcorporatie medewerker'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='woningcorporatie_medewerker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_caseversion_set', to='profiles.Profile', verbose_name='Woningcorporatie medewerker'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'ingediend'), (2, 'afgekeurd'), (3, 'goedgekeurd'), (4, 'in behandeling'), (5, 'ingediend'), (6, 'afgekeurd'), (7, 'goedgekeurd'), (8, 'in behandeling')], default=1, verbose_name='Status'),
        ),
    ]
