# Generated by Django 2.2.10 on 2020-07-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_auto_20200710_0801'),
        ('cases', '0025_auto_20200708_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='woningcorporatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Federation', verbose_name='Woningcorporatie'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='woningcorporatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Federation', verbose_name='Woningcorporatie'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ingediend'), (2, 'Afgekeurd'), (3, 'Goedgekeurd'), (4, 'In behandeling'), (6, 'Afgekeurd'), (7, 'Goedgekeurd'), (8, 'In behandeling')], default=1, verbose_name='Status'),
        ),
    ]
