# Generated by Django 2.2.10 on 2020-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_auto_20200710_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_datum_kennismakingsgesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie datum kennismakingsgesprek'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie datum woonevaluatiegesprek'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_start_intermediaire_verhuur',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie start intermediaire verhuur'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_datum_kennismakingsgesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie datum kennismakingsgesprek'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie datum woonevaluatiegesprek'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_start_intermediaire_verhuur',
            field=models.DateField(blank=True, null=True, verbose_name='Woningcorporatie start intermediaire verhuur'),
        ),
    ]
