# Generated by Django 2.2.10 on 2020-07-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0028_auto_20200710_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Kennismaking wooncorporatie akkoord bewoner datum'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Kennismaking wooncorporatie akkoord zorgaanbieder datum'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Woonevaluatie akkoord bewoner datum'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Woonevaluatie akkoord zorgaanbieder datum'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Kennismaking wooncorporatie akkoord bewoner datum'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Kennismaking wooncorporatie akkoord zorgaanbieder datum'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Woonevaluatie akkoord bewoner datum'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Woonevaluatie akkoord zorgaanbieder datum'),
        ),
    ]
