# Generated by Django 2.2.10 on 2020-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0030_auto_20200717_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='aanvraag_omklap_actief',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Is er sprake van voordracht voor omklap?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='aanvraag_omklap_alle_doelen_behaald',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn alle doelen behaald?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='aanvraag_omklap_steunstructuren',
            field=models.TextField(blank=True, null=True, verbose_name='Op welke steunstructuur / structuren kun je een beroep doen na het moment van omklappen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_afval',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je waar je afval kwijt kunt (afvalbak, glasbak, grof vuil voorzieningen)?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_bewoner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_bewoner_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam Zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_borg_bedrag',
            field=models.TextField(blank=True, null=True, verbose_name='Hoeveel is deze borg?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_borg_betalen',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Moet er borg worden betaald als het huurcontract op naam van de bewoner komt te staan?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_doelen_wonen_huurderschap',
            field=models.TextField(blank=True, null=True, verbose_name='Waar wil jij aan werken dat met wonen en goed huurderschap te maken heeft?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_goed_huurderschap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ik verklaar dat ik me als een goed huurder zal gedragen. Dit houdt in dat ik me houd aan de woonregels, geen overlast veroorzaak en mijn huur op tijd betaal.'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_goede_buur',
            field=models.TextField(blank=True, null=True, verbose_name='Wanneer ben je een goede buur?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_huisregels',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er huisregels in het complex waarmee je rekening moet houden?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_kennisgemaakt_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je kennisgemaakt met je buren?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_kennismaken_buren',
            field=models.TextField(blank=True, null=True, verbose_name='Wil je dat en hoe kun je dat het beste doen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_ondersteuning_medewerker',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe kan de medewerker van de zorgaanbieder en/of de corporatie hierbij ondersteunen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_overlast_melden',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je overlast kunt melden?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_overlast_signalen',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe worden signalen van overlast gedeeld? (verwijzing overlastprotocol)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_overlast_voorkomen',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je overlast kunt voorkomen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_technische_klachten',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je technische klachten kunt melden bij de woningcorporatie?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_wijk',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ervaar je de wijk?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_anders',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er nog andere voorzieningen die de woningcorporatiemedewerker of begeleider wil voorstellen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_behoefte',
            field=models.TextField(blank=True, null=True, verbose_name='Aan welke voorziening heb jij behoefte?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_waar',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je waar voorzieningen zijn waar jij gebruik van kunt maken?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_datum_kennismakingsgesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum kennismakingsgesprek'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum woonevaluatiegesprek'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woningcorporatie_start_intermediaire_verhuur',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum intermediaire verhuur'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_bewoner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_bewoner_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam bewoner'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_zorgaanbieder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_akkoord_zorgaanbieder_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam en functie zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_bijzonderheden_wonen',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er bijzonderheden rond het wonen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_contact_met_buren',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heb je contact met buren?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_contact_met_buren_gewenst',
            field=models.TextField(blank=True, null=True, verbose_name='Zo nee, wil je wel contact? En heb je daar ondersteuning bij nodig?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_contact_met_buren_verloop',
            field=models.TextField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Zo ja, hoe verloopt dat?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_ervaring_wonen',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ervaar je het wonen?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_1_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_1_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen,  stand van zaken'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_2_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_2_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen,  stand van zaken'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_3_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_gepersonaliseerd_doel_3_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen, stand van zaken'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_goed_minder_goed',
            field=models.TextField(blank=True, null=True, verbose_name='Wat gaat goed, wat gaat minder goed?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_huur_betalen_op_tijd',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je de huur elke maand op tijd betaald aan de zorgaanbieder?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_huur_betalen_regeling',
            field=models.TextField(blank=True, null=True, verbose_name='Is er een regeling getroffen en/of extra ondersteuning geregeld?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_moment_volgend_gesprek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wat is een goed moment voor het volgende gesprek?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_netwerk_aanwezig',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je een netwerk in de buurt?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_netwerk_behoefte',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Zo nee, heb je hier behoefte aan?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_netwerk_behoefte_meer_contacten',
            field=models.TextField(blank=True, null=True, verbose_name='Heb je behoefte aan meer of andere contacten in de buurt?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_netwerk_hoe_gaat_dat',
            field=models.TextField(blank=True, null=True, verbose_name='Zo ja, hoe gaat dat?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_omschrijving_balkon_tuin',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet het balkon en/of de tuin er uit?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_omschrijving_portiek',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet het portiek er uit?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_omschrijving_woning',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet de woning er uit?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_overlast_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Ervaar je weleens overlast?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_overlast_buren_gemeld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je dit gemeld bij de corporatie?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_overlast_omwonenden_gemeld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Is er overlast van omwonenden gemeld?'),
        ),
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_overlast_omwonenden_oplossing',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe is daarmee omgegaan? Is het opgelost?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='aanvraag_omklap_actief',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Is er sprake van voordracht voor omklap?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='aanvraag_omklap_alle_doelen_behaald',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn alle doelen behaald?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='aanvraag_omklap_steunstructuren',
            field=models.TextField(blank=True, null=True, verbose_name='Op welke steunstructuur / structuren kun je een beroep doen na het moment van omklappen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_afval',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je waar je afval kwijt kunt (afvalbak, glasbak, grof vuil voorzieningen)?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_bewoner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_bewoner_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_akkoord_zorgaanbieder_naam',
            field=models.TextField(blank=True, null=True, verbose_name='Naam Zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_borg_bedrag',
            field=models.TextField(blank=True, null=True, verbose_name='Hoeveel is deze borg?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_borg_betalen',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Moet er borg worden betaald als het huurcontract op naam van de bewoner komt te staan?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_doelen_wonen_huurderschap',
            field=models.TextField(blank=True, null=True, verbose_name='Waar wil jij aan werken dat met wonen en goed huurderschap te maken heeft?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_goed_huurderschap',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ik verklaar dat ik me als een goed huurder zal gedragen. Dit houdt in dat ik me houd aan de woonregels, geen overlast veroorzaak en mijn huur op tijd betaal.'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_goede_buur',
            field=models.TextField(blank=True, null=True, verbose_name='Wanneer ben je een goede buur?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_huisregels',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er huisregels in het complex waarmee je rekening moet houden?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_kennisgemaakt_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je kennisgemaakt met je buren?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_kennismaken_buren',
            field=models.TextField(blank=True, null=True, verbose_name='Wil je dat en hoe kun je dat het beste doen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_ondersteuning_medewerker',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe kan de medewerker van de zorgaanbieder en/of de corporatie hierbij ondersteunen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_overlast_melden',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je overlast kunt melden?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_overlast_signalen',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe worden signalen van overlast gedeeld? (verwijzing overlastprotocol)'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_overlast_voorkomen',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je overlast kunt voorkomen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_technische_klachten',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je hoe je technische klachten kunt melden bij de woningcorporatie?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_wijk',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ervaar je de wijk?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_anders',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er nog andere voorzieningen die de woningcorporatiemedewerker of begeleider wil voorstellen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_behoefte',
            field=models.TextField(blank=True, null=True, verbose_name='Aan welke voorziening heb jij behoefte?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_wijk_voorzieningen_waar',
            field=models.TextField(blank=True, null=True, verbose_name='Weet je waar voorzieningen zijn waar jij gebruik van kunt maken?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_datum_kennismakingsgesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum kennismakingsgesprek'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum woonevaluatiegesprek'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woningcorporatie_start_intermediaire_verhuur',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum intermediaire verhuur'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_bewoner',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_bewoner_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_bewoner_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam bewoner'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_zorgaanbieder',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_zorgaanbieder_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_akkoord_zorgaanbieder_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam en functie zorgaanbieder'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_bijzonderheden_wonen',
            field=models.TextField(blank=True, null=True, verbose_name='Zijn er bijzonderheden rond het wonen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_contact_met_buren',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Heb je contact met buren?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_contact_met_buren_gewenst',
            field=models.TextField(blank=True, null=True, verbose_name='Zo nee, wil je wel contact? En heb je daar ondersteuning bij nodig?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_contact_met_buren_verloop',
            field=models.TextField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Zo ja, hoe verloopt dat?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_ervaring_wonen',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ervaar je het wonen?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_1_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_1_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='1. Gepersonaliseerd doel rondom het wonen,  stand van zaken'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_2_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_2_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='2. Gepersonaliseerd doel rondom het wonen,  stand van zaken'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_3_behaald',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen behaald'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_gepersonaliseerd_doel_3_stand_van_zaken',
            field=models.TextField(blank=True, null=True, verbose_name='3. Gepersonaliseerd doel rondom het wonen, stand van zaken'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_goed_minder_goed',
            field=models.TextField(blank=True, null=True, verbose_name='Wat gaat goed, wat gaat minder goed?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_huur_betalen_op_tijd',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je de huur elke maand op tijd betaald aan de zorgaanbieder?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_huur_betalen_regeling',
            field=models.TextField(blank=True, null=True, verbose_name='Is er een regeling getroffen en/of extra ondersteuning geregeld?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_moment_volgend_gesprek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wat is een goed moment voor het volgende gesprek?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_netwerk_aanwezig',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je een netwerk in de buurt?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_netwerk_behoefte',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Zo nee, heb je hier behoefte aan?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_netwerk_behoefte_meer_contacten',
            field=models.TextField(blank=True, null=True, verbose_name='Heb je behoefte aan meer of andere contacten in de buurt?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_netwerk_hoe_gaat_dat',
            field=models.TextField(blank=True, null=True, verbose_name='Zo ja, hoe gaat dat?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_omschrijving_balkon_tuin',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet het balkon en/of de tuin er uit?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_omschrijving_portiek',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet het portiek er uit?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_omschrijving_woning',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe ziet de woning er uit?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_overlast_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Ervaar je weleens overlast?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_overlast_buren_gemeld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je dit gemeld bij de corporatie?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_overlast_omwonenden_gemeld',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Is er overlast van omwonenden gemeld?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_overlast_omwonenden_oplossing',
            field=models.TextField(blank=True, null=True, verbose_name='Hoe is daarmee omgegaan? Is het opgelost?'),
        ),
    ]
