# Generated by Django 2.2.10 on 2020-07-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0031_auto_20200720_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_contact_met_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je contact met buren?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_contact_met_buren',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ja'), (2, 'Nee')], null=True, verbose_name='Heb je contact met buren?'),
        ),
    ]
