# Generated by Django 2.2.10 on 2020-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_auto_20200720_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='woonevaluatie_contact_met_buren_verloop',
            field=models.TextField(blank=True, null=True, verbose_name='Zo ja, hoe verloopt dat?'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='woonevaluatie_contact_met_buren_verloop',
            field=models.TextField(blank=True, null=True, verbose_name='Zo ja, hoe verloopt dat?'),
        ),
    ]
