# Generated by Django 2.2.10 on 2020-07-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0033_auto_20200720_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='woningcorporatie_datum_woonevaluatiegesprek',
            new_name='kennismaking_woningcorporatie_datum_woonevaluatiegesprek',
        ),
        migrations.RenameField(
            model_name='caseversion',
            old_name='woningcorporatie_datum_woonevaluatiegesprek',
            new_name='kennismaking_woningcorporatie_datum_woonevaluatiegesprek',
        ),
        migrations.AddField(
            model_name='case',
            name='woonevaluatie_woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum woonevaluatiegesprek'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='woonevaluatie_woningcorporatie_datum_woonevaluatiegesprek',
            field=models.DateField(blank=True, null=True, verbose_name='Datum woonevaluatiegesprek'),
        ),
    ]
