# Generated by Django 2.2.10 on 2020-07-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0034_auto_20200722_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='kennismaking_wooncorporatie_moment_volgend_gesprek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wat is een goed moment voor het volgende gesprek?'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_moment_volgend_gesprek',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wat is een goed moment voor het volgende gesprek?'),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ingediend'), (2, 'Afgekeurd'), (3, 'Goedgekeurd'), (4, 'In behandeling'), (6, 'Afgekeurd'), (7, 'Goedgekeurd'), (8, 'In behandeling'), (9, 'In concept')], default=1, verbose_name='Status'),
        ),
    ]
