# Generated by Django 2.2.10 on 2020-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0035_auto_20200722_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='kennismaking_wooncorporatie_goed_huurderschap_naam_bewoner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam bewoner'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='kennismaking_wooncorporatie_goed_huurderschap_naam_bewoner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam bewoner'),
        ),
    ]
