# Generated by Django 2.2.10 on 2020-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0036_auto_20200729_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jonger_dan_26',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nee'), (2, 'Ja: standaard plaatsing jongerenwoning (5 jaar contract bij omklap)'), (3, 'Ja: plaatsing reguliere woning noodzakelijk (onbepaalde tijd bij omklap)'), (4, 'Ja: Plaatsing in een project')], null=True, verbose_name='Plaatsing jonger dan 26 jaar'),
        ),
        migrations.AlterField(
            model_name='caseversion',
            name='jonger_dan_26',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Nee'), (2, 'Ja: standaard plaatsing jongerenwoning (5 jaar contract bij omklap)'), (3, 'Ja: plaatsing reguliere woning noodzakelijk (onbepaalde tijd bij omklap)'), (4, 'Ja: Plaatsing in een project')], null=True, verbose_name='Plaatsing jonger dan 26 jaar'),
        ),
    ]
