# Generated by Django 2.2.10 on 2020-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0037_auto_20200821_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='aanvraagurgentie_akkoord_client',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='case',
            name='aanvraagurgentie_akkoord_client_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='case',
            name='aanvraagurgentie_akkoord_client_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam cliënt'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_client',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_client_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='case',
            name='omklap_akkoord_client_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='aanvraagurgentie_akkoord_client',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='aanvraagurgentie_akkoord_client_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='aanvraagurgentie_akkoord_client_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_client',
            field=models.BooleanField(blank=True, null=True, verbose_name='Akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_client_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Datum akkoord cliënt'),
        ),
        migrations.AddField(
            model_name='caseversion',
            name='omklap_akkoord_client_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam cliënt'),
        ),
    ]
