# Generated by Django 2.2.9 on 2020-02-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('uploaded_file', models.FileField(upload_to='uploads', verbose_name='Bestand')),
                ('uploaded_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Upload datum/tijd')),
                ('saved_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Opgeslagen datum/tijd')),
            ],
            options={
                'verbose_name': 'Bestand',
                'verbose_name_plural': 'Bestanden',
                'ordering': ('title',),
            },
        ),
    ]
