# Generated by Django 2.2.9 on 2020-02-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='saved_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Opgeslagen datum/tijd'),
        ),
    ]
