# Generated by Django 2.2.9 on 2020-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20200219_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='saved_datetime',
            new_name='saved',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_datetime',
            new_name='uploaded',
        ),
    ]
