# Generated by Django 2.2.9 on 2020-02-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200219_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Type naam')),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-uploaded',), 'verbose_name': 'Bestand', 'verbose_name_plural': 'Bestanden'},
        ),
    ]
