# Generated by Django 2.2.9 on 2020-02-20 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200220_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_to_document', to='documents.DocumentType', verbose_name='Type document'),
        ),
    ]
