# Generated by Django 2.2.9 on 2020-02-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('type_name',), 'verbose_name': 'Bestands type', 'verbose_name_plural': 'Bestands types'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='icon',
            field=models.CharField(blank=True, choices=[('form', 'form'), ('checklist', 'checklist')], max_length=50, null=True, verbose_name='Icon'),
        ),
    ]
