# Generated by Django 2.2.9 on 2020-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20200220_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titel'),
        ),
    ]
