# Generated by Django 2.2.9 on 2020-02-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200221_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(blank=True, choices=[('form', 'Formulier'), ('document', 'Document'), ('checklist', 'Sjabloon')], max_length=50, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Type naam'),
        ),
    ]
