# Generated by Django 2.2.10 on 2020-02-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_auto_20200226_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(blank=True, choices=[('form', 'Formulier'), ('document', 'Document'), ('checklist', 'Sjabloon')], max_length=50, null=True, verbose_name='Documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Titel van het document'),
        ),
    ]
