# Generated by Django 2.2.10 on 2020-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200227_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Omschrijving van het document'),
        ),
    ]
