# Generated by Django 2.2.10 on 2020-02-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20200227_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='icon',
            field=models.CharField(choices=[('form', 'Formulier'), ('document', 'Document'), ('checklist', 'Sjabloon')], default='form', max_length=50, verbose_name='Icon'),
        ),
    ]
