# Generated by Django 2.2.10 on 2020-02-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='icon',
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('form', 'Formulier'), ('document', 'Document'), ('checklist', 'Sjabloon')], default='form', max_length=50, verbose_name='Wat voor soort document is het?'),
        ),
    ]
