# Generated by Django 2.2.10 on 2020-04-03 08:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200402_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='field_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[['id', 'ID'], ['client_first_name', 'Client voornaam'], ['client_last_name', 'Client achternaam'], ['geslacht', 'Geslacht'], ['geboortedatum', 'Geboortedatum'], ['emailadres', 'E-mailadres'], ['woningnet_nummer', 'Woningnetnummer'], ['woningnet_geldigheid', 'Geldigheid woninget'], ['centrale_toegang_naam', 'Naam centrale toegang'], ['jonger_dan_26', 'Plaatsing jonger dan 26 jaar'], ['jonger_dan_26_plaatsing_project', 'Plaatsing jonger project'], ['jonger_dan_26_motivatie_contract_onbepaalde', 'Motivatie voor contract onbepaalde tijd jongere'], ['partner_naam', 'Partner naam'], ['partner_geboortedatum', 'Partner geboortedatum'], ['partner_gehuwd', 'Gehuwd?'], ['partner_echtscheiding_rond', 'Echtscheiding rond?'], ['partner_woonsituatie', 'Woonsituatie partner'], ['kinderen', 'Kinderen'], ['centrale_toegang_trajectwijziging_ed', 'Toegang en trajectwijziging / doorstroom en jeugdzorg'], ['trajecthouder_naam', 'Naam instroomfunctionaris of trajecthouder'], ['aanvraag_datum', 'Datum aanvraag'], ['omslagwoning_zorgaanbieder', 'Zorgaanbieder omslagwoning'], ['urgentiecriteria_zinvolle_dagbesteding', 'De cliënt heeft passende zinvolle dagbesteding'], ['urgentiecriteria_functioneert_sociaal_stabiel', 'De cliënt functioneert sociaal stabiel'], ['urgentiecriteria_functioneert_psychisch_stabiel', 'De cliënt functioneert psychisch stabiel'], ['urgentiecriteria_is_financieel_stabiel', 'De cliënt is financieel stabiel'], ['urgentiecriteria_kinderen_gezonde_omgeving', 'De betrokken kinderen hebben een gezonde omgeving'], ['medische_problemen_mbt_traplopen', 'Zijn er medische problemen m.b.t. traplopen?'], ['medische_problemen_wooneisen', 'Zo ja, benedenwoning of woning met lift? Anders?'], ['medische_problemen_bewijslast', 'Voeg medische gegevens toe m.b.t. problematiek'], ['uitsluiting_stadsdeel_argumentatie', 'Uitsluiting stadsdeel, argumentatie']], help_text='De inhoud van een geselecteerd veld wordt zichtbaar voor deze organisatie.', max_length=768, null=True, verbose_name='Cliënt gegevens velden'),
        ),
    ]
