# Generated by Django 2.2.10 on 2020-06-05 13:41

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200604_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rol_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend'), (7, 'Gebruikers beheerder'), (8, 'Federatie beheerder')], max_length=11, null=True, verbose_name='Rol opties voor federatie beheerder'),
        ),
    ]
