# Generated by Django 2.2.10 on 2020-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_auto_20200706_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='federation_type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'ADW'), (2, 'Zorginstelling'), (3, 'Woningcorporatie')], null=True, verbose_name='Federatie type'),
        ),
    ]
