# Generated by Django 2.2.10 on 2020-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0029_auto_20200729_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='federation',
            name='name_form_validation_team',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naam controle afdeling'),
        ),
        migrations.AlterField(
            model_name='federation',
            name='main_email',
            field=models.TextField(blank=True, help_text='Als je meerdere e-mailadressen wil gebruiken, kun je dat doen door ze met een comma te scheiden.', null=True, verbose_name='Standaard e-mailadres(sen)'),
        ),
    ]
