# Generated by Django 2.2.10 on 2020-08-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20200821_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federation',
            name='main_email',
            field=models.TextField(blank=True, help_text='Als je meerdere e-mailadressen wil gebruiken, kun je dat doen door ze met een komma te scheiden.', null=True, verbose_name='Standaard e-mailadres(sen)'),
        ),
    ]
