# Generated by Django 2.2.10 on 2020-03-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200319_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beheerder'), (2, 'Afedeling Wonen gemeente'), (3, 'GGD'), (4, 'Woningcorporatie'), (5, 'Persoonlijk begeleider')], default=1, verbose_name='Gebruiker type'),
        ),
    ]
