# Generated by Django 2.2.10 on 2020-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200326_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beheerder'), (5, 'Persoonlijk begeleider'), (6, 'Onbekent')], default=6, verbose_name='Gebruiker type'),
        ),
    ]
