# Generated by Django 2.2.10 on 2020-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200429_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Redactie'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend'), (7, 'Gebruikers beheerder')], default=6, verbose_name='Gebruiker rol'),
        ),
    ]
