# Generated by Django 2.2.10 on 2020-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200507_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend'), (7, 'Gebruikers beheerder')], default=6, verbose_name='Gebruiker rol'),
        ),
    ]
