# Generated by Django 2.2.10 on 2020-06-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20200604_1529'),
        ('users', '0007_auto_20200513_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_list', to='organizations.Federation', verbose_name='Federatie'),
        ),
    ]
