# Generated by Django 2.2.10 on 2020-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_federation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend'), (7, 'Gebruikers beheerder'), (8, 'Organisatie beheerder')], default=6, verbose_name='Gebruiker rol'),
        ),
    ]
