# Generated by Django 2.2.10 on 2020-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200619_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend'), (7, 'Gebruikers beheerder'), (8, 'Organisatie beheerder'), (9, 'PB & Organisatie beheerder')], default=6, verbose_name='Gebruiker rol'),
        ),
    ]
