# Generated by Django 2.2.10 on 2020-07-16 09:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200708_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Meta'),
        ),
    ]
