# Generated by Django 2.2.10 on 2020-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Redactie'), (2, 'Wonen medewerker'), (4, 'Woningcorporatie medewerker'), (5, 'Persoonlijk begeleider'), (6, 'Onbekend/inactief'), (7, 'Beheerder'), (8, 'Organisatie beheerder'), (9, 'PB & Organisatie beheerder')], default=6, verbose_name='Gebruiker rol'),
        ),
    ]
