# Generated by Django 2.2.10 on 2020-03-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Omschrijving van het moment'),
        ),
    ]
