# Generated by Django 2.2.10 on 2020-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_moment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Sorteer'),
        ),
    ]
