# Generated by Django 2.2.10 on 2020-03-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20200305_1722'),
    ]

    operations = []
