# Generated by Django 2.2.10 on 2020-03-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_moment_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='roles',
        ),
    ]
