# Generated by Django 2.2.10 on 2020-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('timeline', '0006_remove_moment_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='organizations.Organization', verbose_name='Organisaties'),
        ),
    ]
