# Generated by Django 2.2.10 on 2020-05-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_moment_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='form',
            field=models.CharField(blank=True, choices=[['basis-gegevens', 'Basisgegevens cliënt'], ['aanvraag-omslag-en-urgentie', 'Aanvraag omslag en urgentie'], ['aanvraag-omklap', 'Aanvraag omklap']], max_length=100, null=True, verbose_name='Formulier'),
        ),
    ]
