# Generated by Django 2.2.10 on 2020-06-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_moment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='form',
            field=models.CharField(blank=True, choices=[['basis-gegevens', 'Basisgegevens cliënt'], ['aanvraag-omslag-en-urgentie', 'Aanvraag Urgentie onder voorwaarden'], ['aanvraag-omklap', 'Aanvraag Voordracht omklap']], max_length=100, null=True, verbose_name='Formulier'),
        ),
    ]
