# Generated by Django 2.2.10 on 2020-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20200710_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='form',
            field=models.CharField(blank=True, choices=[['aanvraag-omslag-en-urgentie', 'Aanvraag Urgentie onder voorwaarden'], ['aanvraag-omklap', 'Aanvraag Voordracht omklap'], ['evaluatie-wonen', 'Evaluatie wonen'], ['kennismaking-woningcorporatie', 'Kennismaking woningcorporatie']], max_length=100, null=True, verbose_name='Formulier'),
        ),
    ]
